name: "Deploy Coolify Application"
description: "Updates the Docker image of an application and restarts it."
author: "Carlo Zanella"

inputs:
  endpoint:
    description: "API Endpoint"
    required: true
  token:
    description: "Authentication Token"
    required: true
  app_uuid:
    description: "Application UUID"
    required: true
  image_name:
    description: "Docker Image Name"
    required: false
  image_tag:
    description: "Docker Image Tag"
    required: false

runs:
  using: "node20"
  main: "dist/index.js"
