name: "Run Python Script"
description: "Runs a Python script using a specified Python version"

inputs:
  input1:
    description: "First input variable"
    required: true
  input2:
    description: "Second input variable"
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"

    - name: Install dependencies
      run: pip install -r ${{ github.action_path }}/requirements.txt
      shell: bash

    - name: Run script
      run: python ${{ github.action_path }}/main.py
      shell: bash
      env:
        INPUT1: ${{ inputs.input1 }}
        INPUT2: ${{ inputs.input2 }}
